version: '2.0'
services:

  web1:
    build:
      context: ./.docker/web
      dockerfile: Dockerfile-php-7.0-and-redis-3.0.0
    container_name: devweb1
    ports:
      - "8180:80"
    links:
      - redis:devcahce1
    volumes:
      - ./web/html:/var/www/html
    working_dir: /var/www/html

  web2:
    build:
      context: ./.docker/web
      dockerfile: Dockerfile-php-7.0-and-redis-3.1.0
    container_name: devweb2
    ports:
      - "8280:80"
    links:
      - redis:devcahce1
    volumes:
      - ./web/html:/var/www/html
    working_dir: /var/www/html

  web3:
    build:
      context: ./.docker/web
      dockerfile: Dockerfile-php-7.1-and-redis-3.0.0
    container_name: devweb3
    ports:
      - "8380:80"
    links:
      - redis:devcahce1
    volumes:
      - ./web/html:/var/www/html
    working_dir: /var/www/html

  web4:
    build:
      context: ./.docker/web
      dockerfile: Dockerfile-php-7.1-and-redis-3.1.0
    container_name: devweb4
    ports:
      - "8480:80"
    links:
      - redis:devcahce1
    volumes:
      - ./web/html:/var/www/html
    working_dir: /var/www/html
  redis:
    build: ./.docker/cache
    container_name: devcache1
